### ISSUE TITLE
Add co-organisers

### ISSUE THREAD

**Issue by geohacker** [sotm-asia/sotm-asia-2018-website#15]
Let's add IIM Bangalore, and Centre for Internet and Society as co-organisers. @tridip1931 can you help?

**Comment by tridip1931** [comment]
Hi, How do you want to show it? At the hero?
cc: @rasagy

**Comment by geohacker** [comment]
@tridip1931 i think a section after the hero? logo side by side or something.

**Comment by tridip1931** [comment]
This was done. #18
