### ISSUE TITLE
Logo image not properly center aligned. 

### ISSUE THREAD

**Issue by tridip1931** [sotm-asia/sotm-asia-2018-website#23]
![127 0 0 1_5500_index html 2](https://user-images.githubusercontent.com/7458983/38419932-d54d37b8-39bf-11e8-9c23-c709df6c4fc0.png)

**Comment by rasagy** [comment]
[Fixed](https://github.com/sotm-asia/sotm-asia-2018-website/commit/5f6323ec99a0a1019f4043b57d9ab2ccb99ea567)!


![image](https://user-images.githubusercontent.com/1117531/38433716-8be5432a-39e9-11e8-8f70-96f15ec22000.png)
