### ISSUE TITLE
Adding CfS to the website

### ISSUE THREAD

**Issue by jinalfoflia** [sotm-asia/sotm-asia-2018-website#24]
The [CfS](https://github.com/sotm-asia/sotm-asia-2018/issues/25) will go out tomorrow morning 10 am. Should we also have this on the website?

cc: @geohacker @rasagy @tridip1931

**Comment by tridip1931** [comment]
closes #25

**Comment by jinalfoflia** [comment]
Thank you @tridip1931 🎉
