### ISSUE TITLE
Bit.ly everything!

### ISSUE THREAD

**Issue by rasagy** [sotm-asia/sotm-asia-2018-website#27]
Not _everything_, but all important links that take us away from the site (like google forms, google docs etc.) should be wrapped with bit.ly — that helps us better track response (Like: Are many people looking at the sponsorship deck but not reaching out?)

@jinalfoflia Want to help @tridip1931 by creating/listing custom bit.ly for these links:

- [x] CfP form: http://bit.ly/cfp-sotm-asia
- [x] CfS form: http://bit.ly/sotmasia-cfs
- [ ] Blog: http://bit.ly/blog-state-of-the-map-asia

@tridip1931 Once you have the list, can you take a minute and update the links? Thanks! 🙇

**Comment by jinalfoflia** [comment]
Thanks for writing this ticket @rasagy! Have added the required links here and will keep this updated with other links as we add more :)

cc: @tridip1931

**Comment by tridip1931** [comment]
I think this was done. Closing.
