### ISSUE TITLE
Create a Sponsorship Proposal 

### ISSUE THREAD

**Issue by satyaakam** [sotm-asia/sotm-asia-2018-website#3]
Create Sponsorship Proposal doc for Sponsors 
Something on  the lines of [1] suggest if you have better options 
[1] https://docs.google.com/document/d/1s8Q8blg7IJUhGZfLjjkwfOx3CQL_KJ5yVDuEbFbWUcg/edit

**Comment by geohacker** [comment]
https://github.com/sotm-asia/sotm-asia-2018/issues/2
