### ISSUE TITLE
Alternative Design Exploration for website.

### ISSUE THREAD

**Issue by tridip1931** [sotm-asia/sotm-asia-2018-website#30]
![hero](https://user-images.githubusercontent.com/7458983/38778124-b1ce2bd0-40d1-11e8-942d-7357f30998c4.png)

- Exploring typeface, used Heebo which is also a free google font. I feel Dosis looks good on `uppercase`, but it tends to become uncalibrated when used in complete sentences. 
- A topography based pattern in the background to signify the theme of the event

![call](https://user-images.githubusercontent.com/7458983/38778150-4ea0a1fe-40d2-11e8-9ec8-6c56c260c085.png)

- Exploring duotones, @rasagy and I talked about this casually
- Downside is we need relevant hi-res photos that actually portray past sotm events. 

**/cc:** @geohacker @jinalfoflia

**Comment by tridip1931** [comment]
ref: #28

**Comment by tridip1931** [comment]
Subtle svg gradient animation we can use in the background. 
[https://codepen.io/tridipthrizu/pen/qozJOw](https://codepen.io/tridipthrizu/pen/qozJOw)
![svg-animation](https://user-images.githubusercontent.com/7458983/38778484-ed461cd0-40d7-11e8-9800-94ae389ec00c.gif)

**Comment by rasagy** [comment]
Thanks for working on this @tridip1931. 

Quick questions:

- Looking at #28, how does the current approach scale? Are you recommending having one CTA in the first section, and then two-column boxes for other sections (About SOTM, Venue, Recap, Sponsors etc)? Or do you recommend mixing two-columns and single rows?
- For a mobile view, do you plan to switch the vertical logo or will you just let the section on right come below?
- Did you explore any other type for pairing with Dosis? Any other type with better hinting?
- Love the pattern! If you feel the animation is well supported across browsers, then we should do that as well. <3

**Comment by tridip1931** [comment]
We discussed this offline, some of the pointers below:
- We will prioritize CTA on the hero. If we add all the actions on hero section, it will get cluttered and lose its importance. 
- We will implement max-width for devices >1200 (per bootstrap guidelines) for the two-columns rows. 
- On mobile, logo (without text) will be visible at the centre of the nav bar
- For supporting browsers, it depends who are our demographics. Since bootstrap now uses flexbox, they are usually supported by browsers which already support svg animations. 
For more you can refer to [MDN](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/animate)
- For type, I gravitated towards sans-serif family (similar to Roboto). Do you have any suggestions?
