### ISSUE TITLE
Add sponsors and partners

### ISSUE THREAD

**Issue by geohacker** [sotm-asia/sotm-asia-2018-website#34]
@tridip1931 @jinalfoflia - let's use this ticket to track sponsors and partners we should add to the website. 

1. OpenCageData Ltd.
2. Namma Bengaluru Foundation
3. Medianama

@tridip1931 will this be dependent on #33? Can you help put a timeline on this, thank you!

**Comment by geohacker** [comment]
> Or I can create different PR for the blockers and merge #33 along with this sponsors.

This is fine by me - we need to move faster on the website than the speed we've been at so far. 

> What is the difference between partners, sponsors and organizers?

Partners - brings value through their networks and do outreach or inform the content of the event. No $$
Sponsors - brings $$
Organisers - runs the event doing logistics, finance and other administration.

**Comment by tridip1931** [comment]
I am good to merge #33 Added new responsive fixes.
Can you check the content that needs to hidden for now? 
Like I know buy tickets can be replaced with coming soon on something.

**Comment by tridip1931** [comment]
👋 @geohacker 
New iteration on sponsor 👉 https://invis.io/H8NYA1I9236#/318839214_Extra_Large__Desktops_-_12_Col-1-1

**Comment by geohacker** [comment]
@tridip1931 thank you. I think we want to use up the dead space in the div and make the logos bigger. Can you make the logos proportional to the sponsor slab? Facebook should be bigger (gold), Mapbox (bit smaller) etc.
