### ISSUE TITLE
Venue + Visa information page

### ISSUE THREAD

**Issue by jinalfoflia** [sotm-asia/sotm-asia-2018-website#46]
Opening this ticket to capture the following:

Thank you @poornibadrinath for all your research on finding accommodation options for attendees, here's the draft of the blog post - https://docs.google.com/document/d/1JoCxkU6otYYcCqU6tJZFnI1rox6zn9Pgy-5G4Wqm9GU/edit?ts=5bb8cee4#

@jeethjoseph is working on information for Visa for the attendees who are flying from different places. 

@poornibadrinath @tridip1931 @jeethjoseph, can you please coordinate and work on making this a page on the website -- so that we can direct folks to a single place for all the information they need.

cc: @geohacker

**Comment by poornibadrinath** [comment]
The blog post is [here](https://docs.google.com/document/d/1JoCxkU6otYYcCqU6tJZFnI1rox6zn9Pgy-5G4Wqm9GU/edit#) and this is the [map link](https://api.mapbox.com/styles/v1/poorni-badrinath/cjn1t1j7a564n2sprlg03xzgo.html?fresh=true&title=true&access_token=pk.eyJ1IjoicG9vcm5pLWJhZHJpbmF0aCIsImEiOiJjaWVoOGFiNWUwMDl2c3JtMXBzcWluaDN5In0.uunHEpdx8grTpnmTwTwxHA#10.6/12.995648/77.664947/360)

@tridip1931 what are the next actions here that are on me?

**Comment by poornibadrinath** [comment]
@geohacker, it would be great if you could also go through the blog post and let me know if there are any changes to make. To the post or to the map. 

/cc: @jinalfoflia

**Comment by jeethjoseph** [comment]
Created a concise piece on Visas. Let me know what you think.
[https://docs.google.com/document/d/11LVtlXTqt9GJQnrpBsDg9xU0eFtHJa3TbhzOP20PoSI/edit?usp=sharing]

**Comment by jinalfoflia** [comment]
>Created a concise piece on Visas. Let me know what you think.
https://docs.google.com/document/d/11LVtlXTqt9GJQnrpBsDg9xU0eFtHJa3TbhzOP20PoSI/edit?usp=sharing

This looks great @jeethjoseph! Thanks so much for pulling this together. Have left a comment on the conference visa thing, other than that, it all looks good to me. 

> https://docs.google.com/document/d/19lDVyxdO-FA2NoVpOMhlNOqROKy1bi1J1v5cfu_HGSI/edit

@poornibadrinath the doc looks good to me, have suggested a couple of things, post that over to you all to move all this to the website. Also, can you please add **emergency numbers** that they could reach out to in case of help?

As I suggested in the [comment above](https://github.com/sotm-asia/sotm-asia-2018-website/issues/46#issuecomment-428316428) it'll be good to change the color of the markers as they blend with the map and are hard to see. 

cc: @tridip1931 @geohacker

**Comment by poornibadrinath** [comment]
Whose emergency numbers to provide in the doc? I will give mine, but we need one other person's probably. 

Posting the [venue and directions doc](https://docs.google.com/document/d/19lDVyxdO-FA2NoVpOMhlNOqROKy1bi1J1v5cfu_HGSI/edit#) here after changes, do let me know if there are any more changes to do :) 

Also, sorry for the delay in map changes, will have it ready by tomorrow. 

/cc: @jinalfoflia @geohacker

**Comment by govvin** [comment]
> Created a concise piece on Visas. Let me know what you think.
> https://docs.google.com/document/d/11LVtlXTqt9GJQnrpBsDg9xU0eFtHJa3TbhzOP20PoSI/edit?usp=sharing

It would be very helpful to identify an India-based contact person, address and contact number which is required in the e-visa application:
![image](https://user-images.githubusercontent.com/5821688/46842963-32f5e680-ce03-11e8-9cc4-4feac4b356f5.png)

**Comment by jinalfoflia** [comment]
@govvin thank you for pointing this, we have a created a form for folks to ask for invitation letter for the conference. The invitation letter will have all the details they need/require: https://goo.gl/forms/EwrY8os0uMCqlQlv2

**Comment by jinalfoflia** [comment]
>Whose emergency numbers to provide in the doc? I will give mine, but we need one other person's probably.

@poornibadrinath here by emergency numbers I meant we could give the ambulence, police, etc ones. At some point we'll have to give someone's number from the team for being the direct contact, I'm not sure if it's a good idea to do that. Let's discuss that during our next catch up. For now let's just add the common emergency numbers.

**Comment by govvin** [comment]
In the last SoTM, Telegram was in prevalent use. I suppose, one of the reasons is that one can give away their telegram username, for other people to call/message you, without giving out a phone number. Needless to say, it requires an Internet connection.

Food for thought.

**Comment by jinalfoflia** [comment]
The page is live, closing this!
