### ISSUE TITLE
Can't switch from program page to venue page 

### ISSUE THREAD

**Issue by jinalfoflia** [sotm-asia/sotm-asia-2018-website#53]
I encountered this issue when I tried to directly switch from the program page on the website to the venue page on the website, it does not switch. It switches fine if we are on the venue page and and go to the program page. 

Program page returns this URL when we try to switch: http://stateofthemap.asia/program/#

If we go back to the home page and then switch to the venue page, it works fine. 

@tridip1931 can you please look into this? Thank you! 

cc: @geohacker

**Comment by geohacker** [comment]
Thank you for catching. Just fixed
