### ISSUE TITLE
Copy

### ISSUE THREAD

**Issue by geohacker** [sotm-asia/sotm-asia-2018-website#6]
@tridip1931 @rasagy @jinalfoflia  - I took a stab at the lede and copy as we build the homepage. I think we should keep it really simple. 

### Lede:

_State of the Map Asia is in Bengaluru this year, bringing together participants from across the region to discuss challenges, spread awareness, learn from each other, and celebrate many years of mapping together._

or 

_The OpenStreetMap Community invites everyone to Bangalore to celebrate the growth of OpenStreetMap in Asia at the annual conference in November. This year, we hope to bring together participants from across the region to discuss challenges, strengthen the community, and learn from each other._

could add or spin this into the sentences:

_Bangalore has the most vibrant technology industry and cultural heritage to be the host this year. _

### Venue

as soon as we we figure out the venue we'll write something

### CoC

let's use the same as global https://github.com/sotm-asia/sotm-asia-2018/issues/9

Please feel free to edit! Thank you

**Comment by tridip1931** [comment]
Moving over to new tickets. Closing this.
